// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzCPU0tp7xkjBgDUJvzBVYijU9ex3iNtw',
    appId: '1:734599098605:web:0fea39b7a1a68231b89ce4',
    messagingSenderId: '734599098605',
    projectId: 'blood-bank-android-9ef0f',
    authDomain: 'blood-bank-android-9ef0f.firebaseapp.com',
    storageBucket: 'blood-bank-android-9ef0f.appspot.com',
    measurementId: 'G-6JC0DYL9P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpxcDsx_0bmRCWaN2dhYJgwmZ02k1h_Yk',
    appId: '1:734599098605:android:de6e4feb2fceeb0fb89ce4',
    messagingSenderId: '734599098605',
    projectId: 'blood-bank-android-9ef0f',
    storageBucket: 'blood-bank-android-9ef0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRWLfijWqzmkX5v9KaVyMZ8tV6AZDGBo',
    appId: '1:734599098605:ios:9bb1760fe598ec63b89ce4',
    messagingSenderId: '734599098605',
    projectId: 'blood-bank-android-9ef0f',
    storageBucket: 'blood-bank-android-9ef0f.appspot.com',
    androidClientId: '734599098605-iog4ne4dqesmugnljm1nqi3prfes62i2.apps.googleusercontent.com',
    iosClientId: '734599098605-ui815ihu4v7vf46pmopp5basjjtt60ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyRWLfijWqzmkX5v9KaVyMZ8tV6AZDGBo',
    appId: '1:734599098605:ios:3f497c4daa2a04b3b89ce4',
    messagingSenderId: '734599098605',
    projectId: 'blood-bank-android-9ef0f',
    storageBucket: 'blood-bank-android-9ef0f.appspot.com',
    androidClientId: '734599098605-iog4ne4dqesmugnljm1nqi3prfes62i2.apps.googleusercontent.com',
    iosClientId: '734599098605-lno6os2s1ffc5ich3k4vl50fb58knm0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBank.RunnerTests',
  );
}
